-- =========================================================
-- IWA JUSTICE V2 - MIGRATION
-- À exécuter UNE SEULE FOIS dans Supabase > SQL Editor
-- =========================================================

-- 1) Ajouter les champs de suivi judiciaire aux plaintes
alter table public.plaintes
add column if not exists responsable text,
add column if not exists date_audience date,
add column if not exists decision text,
add column if not exists sanction text,
add column if not exists archive boolean not null default false,
add column if not exists updated_at timestamp with time zone default now();

-- 2) Créer la table des notes internes
create table if not exists public.notes_plainte (
  id bigint generated by default as identity primary key,
  plainte_id bigint not null references public.plaintes(id) on delete cascade,
  contenu text not null,
  auteur_email text,
  created_at timestamp with time zone not null default now()
);

-- 3) Activer RLS
alter table public.plaintes enable row level security;
alter table public.notes_plainte enable row level security;

-- 4) Nettoyer les anciennes policies
drop policy if exists "autoriser insertion publique" on public.plaintes;
drop policy if exists "autoriser lecture publique" on public.plaintes;
drop policy if exists "autoriser modification publique" on public.plaintes;
drop policy if exists "autoriser suppression publique" on public.plaintes;
drop policy if exists "public_insert_plainte" on public.plaintes;
drop policy if exists "admin_select_plainte" on public.plaintes;
drop policy if exists "admin_update_plainte" on public.plaintes;
drop policy if exists "admin_delete_plainte" on public.plaintes;

drop policy if exists "admin_select_notes" on public.notes_plainte;
drop policy if exists "admin_insert_notes" on public.notes_plainte;
drop policy if exists "admin_delete_notes" on public.notes_plainte;

-- 5) Le public peut uniquement créer une plainte
create policy "public_insert_plainte"
on public.plaintes
for insert
to anon, authenticated
with check (true);

-- 6) Les admins peuvent lire/modifier/supprimer les plaintes
create policy "admin_select_plainte"
on public.plaintes
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_update_plainte"
on public.plaintes
for update
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_delete_plainte"
on public.plaintes
for delete
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- 7) Seuls les admins ont accès aux notes internes
create policy "admin_select_notes"
on public.notes_plainte
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_insert_notes"
on public.notes_plainte
for insert
to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_delete_notes"
on public.notes_plainte
for delete
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
